name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Git Bash
      run: choco install git
      shell: powershell

    - name: Configure project
      run: ./configure
      shell: bash

    - name: Build project
      run: make
      shell: bash

    - name: Run tests
      run: make check
      shell: bash

    - name: Run distcheck
      run: make distcheck
      shell: bash
