name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: choco install make

      - name: Configure project
        run: ./configure

      - name: Build project
        run: make

      - name: Run tests
        run: make check

      - name: Run distcheck
        run: make distcheck
